export const types = {
  GET_WALLET_DATA: "GET_WALLET_DATA",
  GET_ALL_PUBLISHER_DATA: "GET_ALL_PUBLISHER_DATA",
  GET_INDIVIDUAL_PUBLISHER_DATA: "GET_INDIVIDUAL_PUBLISHER_DATA",
  INDIVIDUAL_PUBLISHER_DATA_EDITED_STATUS:
    "INDIVIDUAL_PUBLISHER_DATA_EDITED_STATUS",
  RENDER_ADD_PUBLISHER_FORM: "RENDER_ADD_PUBLISHER_FORM",
  GET_WALLET_DATA_REQUEST: "GET_WALLET_DATA_REQUEST",
};
